### ISSUE TITLE
Enable cross-origin resource sharing

### ISSUE THREAD

**Issue by simon04** [jkroll20/tlgbackend#1]
Please set the `Access-Control-Allow-Origin` HTTP header to enable cross-origin resource sharing and allow JavaScript websites to use https://tools.wmflabs.org/render/tlgbe/tlgwsgi.py

Use case: https://github.com/simon04/locator-tool/issues/22#issuecomment-328163700

**Comment by kroll-j** [comment]
Should be working now, if it doesn't please let me know.
